# Generated by Django 5.1.1 on 2024-09-30 17:03

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='использован пригласительный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Укажите номер телефона в формате 79991233221', max_length=16, unique=True, validators=[users.validators.phone_validator], verbose_name='Телефон'),
        ),
    ]
