# Generated by Django 5.1.1 on 2024-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Откуда Вы?', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.TextField(default=0, max_length=10, verbose_name='Код для приглашений'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, help_text='Укажите номер телефона в формате...', max_length=16, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
