# Generated by Django 5.1.1 on 2024-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ref_code_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.TextField(default=0, max_length=10, verbose_name='использован пригласительный код'),
        ),
    ]
