# Generated by Django 5.1.1 on 2024-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='использован пригласительный код'),
        ),
    ]
